site_name: SimulAI Docs

theme:
  name: "material"
  features:
      - search.highlight
      - search.suggest

plugins:
  - search
  - autorefs
  - mkdocstrings 

nav:
  - index.md
  - simulai_io.md
  - simulai_residuals.md
  - simulai_regression.md
  - simulai_models.md
