site_name: SimulAI's Documentation
repo_name: IBM/simulai
repo_url: https://github.com/IBM/simulai

theme:
  name: simple-blog
  features:
      - search.highlight
      - search.suggest
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: red
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true

markdown_extensions:
  - toc:
      permalink: "#"

plugins:
  - search
  - autorefs
  - mkdocstrings 

nav:
  - Home: index.md
  - Modules:
    - IO:
      - simulai_io.md
    - File:
      - simulai_file.md
    - Batching:
      - simulai_batching.md
    - Activations:
      - simulai_activations.md
    - Parallel:
      - simulai_parallel.md
  - Subpackages:
    - Symbolic Manipulation:
      - simulai_residuals.md
    - Regression/Neural Networks:
      - Dense Networks:
        - simulai_regression/simulai_dense.md
      - OpInf:
        - simulai_regression/simulai_opinf.md
    - ROM:
      - simulai_rom/simulai_rom.md
    - Models:
      - Transformer:
        - simulai_models/simulai_models_transformer.md
      - DeepONet:
        - simulai_models/simulai_models_deeponet.md
      - AutoEncoder:
        - simulai_models/simulai_models_autoencoder.md
      - U-Net:
        - simulai_models/simulai_models_unet.md
